# Название приложения
app = "catanvlad"

# Регион, где будет размещено приложение
primary_region = "ams"
[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "False"
  SECRET_KEY = "django-insecure-*mn-=*8cc)_jw(^c($+k&_q!@4mon81xo)0#*vle==owx-axv4"
  ALLOWED_HOSTS = ".fly.dev"
  DJANGO_SETTINGS_MODULE = "DjangoProject1.settings"
  REDIS_URL = "redis://default:077fd3d4edf44aef88f0578ef37074ee@fly-catan-7p43pg.upstash.io:6379/1"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 5
