app = "my-django-app"  # например: "django-app"

primary_region = "ams"  # можно поменять на ближайший к тебе регион (ams, fra, iad, sin и т.д.)

[build]
  image = "yourdockerhubusername/your-django-app:latest"  # если билдим образ вручную и пушим на DockerHub

[env]
  DEBUG = "False"
  SECRET_KEY = 'django-insecure-*mn-=*8cc)_jw(^c($+k&_q!@4mon81xo)0#*vle==owx-axv4'
  ALLOWED_HOSTS = ".fly.dev"
  REDIS_URL = "redis://default:@redis.internal:6379"
  DJANGO_SETTINGS_MODULE = "DjangoProject1.settings"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 5
